IN_CAR = False # Disables GPIO and CAN for testing outside of vehicle
DEBUG = True

DASH_UPDATE_FREQUENCY = 60 # Hz
BUTTON_TRANSMIT_INTERVAL = 50 # ms
CAN_RECV_TIMEOUT = 0.005 # s

CAN_RESERVED_GPIO = {7, 8, 9, 10, 11, 23, 25}
CAN_NRST_GPIO = 5
CAN_STBY_GPIO = 6
CAN_BASE_ID = 0x750
CAN_EXTENDED_ID = True

DRIVE_BUTTON_GPIO = 2
DRIVE_LED_GPIO = 3
NEUTRAL_BUTTON_GPIO = 4
NEUTRAL_LED_GPIO = 17
REVERSE_BUTTON_GPIO = 27
REVERSE_LED_GPIO = 22
IMD_LED_GPIO = 13
BMS_LED_GPIO = 19
