IN_CAR = True # Disables GPIO and CAN for testing outside of vehicle
DEBUG = True

DASH_UPDATE_FREQUENCY = 60 # Hz
BUTTON_TRANSMIT_INTERVAL = 50 # ms
CAN_RECV_TIMEOUT = 0.005 # s

CAN_RESERVED_GPIO = {7, 8, 9, 10, 11, 23, 25}
CAN_NRST_GPIO = 5
CAN_STBY_GPIO = 6
CAN_BASE_ID = 0x750
CAN_EXTENDED_ID = False

CAN_INVERTER1_BASE = 0x6C0
CAN_INVERTER2_BASE = 0x5C0
CAN_INVERTER_EXTENDED_ID = True

CAN_BMS_BASE = 0x320
CAN_BMS_EXTENDED_ID = False

DRIVE_BUTTON_GPIO = 22
DRIVE_LED_GPIO = 27
NEUTRAL_BUTTON_GPIO = 20
NEUTRAL_LED_GPIO = 16
REVERSE_BUTTON_GPIO = 13
REVERSE_LED_GPIO = 19
IMD_LED_GPIO = 23
BMS_LED_GPIO = 24

BUTTON1_GPIO = 0
BUTTON2_GPIO = 0
SWITCH1_POS1_GPIO = 0
SWITCH1_POS2_GPIO = 0
SWITCH2_POS1_GPIO = 0
SWITCH2_POS2_GPIO = 0